apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-hostpath
spec:
  containers:
  - name: nginx
    image: nginx:1.29.3
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 20
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
    volumeMounts:
    - name: workdir-volume
      mountPath: /workdir
  volumes:
  - name: workdir-volume
    hostPath:
      path: /tmp/workdir
      type: DirectoryOrCreate
