apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret-volume
  namespace: default
spec:
  containers:
  - name: my-container
    image: nginx:1.29.3
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
    - name: my-secret-volume
      mountPath: "/etc/my-secret"
      readOnly: true
  volumes:
  - name: my-secret-volume
    secret:
      secretName: my-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: default
type: Opaque
data:
  # The values are base64 encoded.
  # 'username' -> dXNlcg==
  # 'password' -> cGFzc3dvcmQ=
  username: dXNlcg==
  password: cGFzc3dvcmQ=
