apiVersion: v1
kind: Pod
metadata:
  name: resource-demo-pod
spec:
  containers:
  - name: demo-container
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        # "200m" means 200 millicores (0.2 CPU core).
        cpu: "200m"
        # "256Mi" means 256 Mebibytes of memory.
        memory: "256Mi"
